[package]
name = "integer-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
chrono = "0.4.39"
octocrab = "0.43.0"
rug = "1.26.1"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
